### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by yejinc** [yejinc/wanted_pre_onboarding#1]
# to-do list

### prototype
- [x] mock-up with Figma
### install
- [x]  react
- [x]  sass
- [ ] [browser happy] (https://browsehappy.com/)

## assets
-  [ ] 

### base
- [x] normalizer
- [x] reset
- [x] globals
### mixins
- [x] flexbox
- [x] positions
- [x] responsive
- [x] scrollbar
- [x] text-styles
### constants
- [x] breakpoints
- [x] colours
- [x] grids
- [x] typography
- [x] z-index
- [ ] box-shadows
### modules
- [x] icons
- [x] button
### layouts
- [x] global-header
- [x] gnb
- [x] grids
- [ ] lnb
### components
- [x] gnb-icon-buttons
- [x] gnb-nav

### TBD
